window.esdocSearchIndex = [
  [
    "popcorn-api/src/models/anime.js~anime",
    "variable/index.html#static-variable-Anime",
    "<span>Anime</span> <span class=\"search-result-import-path\">popcorn-api/src/models/Anime.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/controllers/animes.js~animes",
    "class/src/controllers/animes.js~Animes.html",
    "<span>Animes</span> <span class=\"search-result-import-path\">popcorn-api/src/controllers/animes.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/extractors/baseextractor.js~baseextractor",
    "class/src/providers/extractors/baseextractor.js~BaseExtractor.html",
    "<span>BaseExtractor</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/extractors/baseextractor.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/cli.js~cli",
    "class/src/cli.js~CLI.html",
    "<span>CLI</span> <span class=\"search-result-import-path\">popcorn-api/src/cli.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/shows/eztv.js~eztv",
    "class/src/providers/shows/eztv.js~EZTV.html",
    "<span>EZTV</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/shows/eztv.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/controllers/exports.js~exports",
    "class/src/controllers/exports.js~Exports.html",
    "<span>Exports</span> <span class=\"search-result-import-path\">popcorn-api/src/controllers/exports.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/anime/extratorrent.js~extratorrent",
    "class/src/providers/anime/extratorrent.js~ExtraTorrent.html",
    "<span>ExtraTorrent</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/anime/extratorrent.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/anime/nyaa.js~extratorrent",
    "class/src/providers/anime/nyaa.js~ExtraTorrent.html",
    "<span>ExtraTorrent</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/anime/nyaa.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/movies/extratorrent.js~extratorrent",
    "class/src/providers/movies/extratorrent.js~ExtraTorrent.html",
    "<span>ExtraTorrent</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/movies/extratorrent.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/shows/extratorrent.js~extratorrent",
    "class/src/providers/shows/extratorrent.js~ExtraTorrent.html",
    "<span>ExtraTorrent</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/shows/extratorrent.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/extractors/animeextractor.js~extractor",
    "class/src/providers/extractors/animeextractor.js~Extractor.html",
    "<span>Extractor</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/extractors/animeextractor.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/extractors/movieextractor.js~extractor",
    "class/src/providers/extractors/movieextractor.js~Extractor.html",
    "<span>Extractor</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/extractors/movieextractor.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/extractors/showextractor.js~extractor",
    "class/src/providers/extractors/showextractor.js~Extractor.html",
    "<span>Extractor</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/extractors/showextractor.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/helpers/animehelper.js~helper",
    "class/src/providers/helpers/animehelper.js~Helper.html",
    "<span>Helper</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/helpers/animehelper.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/helpers/moviehelper.js~helper",
    "class/src/providers/helpers/moviehelper.js~Helper.html",
    "<span>Helper</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/helpers/moviehelper.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/helpers/showhelper.js~helper",
    "class/src/providers/helpers/showhelper.js~Helper.html",
    "<span>Helper</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/helpers/showhelper.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/anime/horriblesubs.js~horriblesubs",
    "class/src/providers/anime/horriblesubs.js~HorribleSubs.html",
    "<span>HorribleSubs</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/anime/horriblesubs.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/controllers/index.js~index",
    "class/src/controllers/index.js~Index.html",
    "<span>Index</span> <span class=\"search-result-import-path\">popcorn-api/src/controllers/index.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/index.js~index",
    "class/src/index.js~Index.html",
    "<span>Index</span> <span class=\"search-result-import-path\">popcorn-api/src/index.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/anime/kat.js~kat",
    "class/src/providers/anime/kat.js~KAT.html",
    "<span>KAT</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/anime/kat.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/movies/kat.js~kat",
    "class/src/providers/movies/kat.js~KAT.html",
    "<span>KAT</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/movies/kat.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/shows/kat.js~kat",
    "class/src/providers/shows/kat.js~KAT.html",
    "<span>KAT</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/shows/kat.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/config/logger.js~logger",
    "class/src/config/logger.js~Logger.html",
    "<span>Logger</span> <span class=\"search-result-import-path\">popcorn-api/src/config/logger.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/models/movie.js~movie",
    "variable/index.html#static-variable-Movie",
    "<span>Movie</span> <span class=\"search-result-import-path\">popcorn-api/src/models/Movie.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/controllers/movies.js~movies",
    "class/src/controllers/movies.js~Movies.html",
    "<span>Movies</span> <span class=\"search-result-import-path\">popcorn-api/src/controllers/movies.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/config/constants.js~promise",
    "variable/index.html#static-variable-Promise",
    "<span>Promise</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/routes.js~routes",
    "class/src/config/routes.js~Routes.html",
    "<span>Routes</span> <span class=\"search-result-import-path\">popcorn-api/src/config/routes.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/scraper.js~scraper",
    "class/src/scraper.js~Scraper.html",
    "<span>Scraper</span> <span class=\"search-result-import-path\">popcorn-api/src/scraper.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/config/setup.js~setup",
    "class/src/config/setup.js~Setup.html",
    "<span>Setup</span> <span class=\"search-result-import-path\">popcorn-api/src/config/setup.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/models/show.js~show",
    "variable/index.html#static-variable-Show",
    "<span>Show</span> <span class=\"search-result-import-path\">popcorn-api/src/models/Show.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/controllers/shows.js~shows",
    "class/src/controllers/shows.js~Shows.html",
    "<span>Shows</span> <span class=\"search-result-import-path\">popcorn-api/src/controllers/shows.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/util.js~util",
    "class/src/util.js~Util.html",
    "<span>Util</span> <span class=\"search-result-import-path\">popcorn-api/src/util.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/providers/movies/yts.js~yts",
    "class/src/providers/movies/yts.js~YTS.html",
    "<span>YTS</span> <span class=\"search-result-import-path\">popcorn-api/src/providers/movies/yts.js</span>",
    "class"
  ],
  [
    "popcorn-api/src/config/constants.js~animemap",
    "variable/index.html#static-variable-animeMap",
    "<span>animeMap</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~collections",
    "variable/index.html#static-variable-collections",
    "<span>collections</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~crontime",
    "variable/index.html#static-variable-cronTime",
    "<span>cronTime</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~dbhosts",
    "variable/index.html#static-variable-dbHosts",
    "<span>dbHosts</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~dbname",
    "variable/index.html#static-variable-dbName",
    "<span>dbName</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~extratorrentanimeproviders",
    "variable/index.html#static-variable-extratorrentAnimeProviders",
    "<span>extratorrentAnimeProviders</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~extratorrentmovieproviders",
    "variable/index.html#static-variable-extratorrentMovieProviders",
    "<span>extratorrentMovieProviders</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~extratorrentshowproviders",
    "variable/index.html#static-variable-extratorrentShowProviders",
    "<span>extratorrentShowProviders</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~fanart",
    "variable/index.html#static-variable-fanart",
    "<span>fanart</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~katanimeproviders",
    "variable/index.html#static-variable-katAnimeProviders",
    "<span>katAnimeProviders</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~katmovieproviders",
    "variable/index.html#static-variable-katMovieProviders",
    "<span>katMovieProviders</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~katshowproviders",
    "variable/index.html#static-variable-katShowProviders",
    "<span>katShowProviders</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~master",
    "variable/index.html#static-variable-master",
    "<span>master</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~maxwebrequest",
    "variable/index.html#static-variable-maxWebRequest",
    "<span>maxWebRequest</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~moviemap",
    "variable/index.html#static-variable-movieMap",
    "<span>movieMap</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~nyaaanimeproviders",
    "variable/index.html#static-variable-nyaaAnimeProviders",
    "<span>nyaaAnimeProviders</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~omdb",
    "variable/index.html#static-variable-omdb",
    "<span>omdb</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~pagesize",
    "variable/index.html#static-variable-pageSize",
    "<span>pageSize</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~port",
    "variable/index.html#static-variable-port",
    "<span>port</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~server",
    "variable/index.html#static-variable-server",
    "<span>server</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~showmap",
    "variable/index.html#static-variable-showMap",
    "<span>showMap</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~statusfile",
    "variable/index.html#static-variable-statusFile",
    "<span>statusFile</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~tempdir",
    "variable/index.html#static-variable-tempDir",
    "<span>tempDir</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~timezone",
    "variable/index.html#static-variable-timeZone",
    "<span>timeZone</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~tmdb",
    "variable/index.html#static-variable-tmdb",
    "<span>tmdb</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~trakt",
    "variable/index.html#static-variable-trakt",
    "<span>trakt</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~tvdb",
    "variable/index.html#static-variable-tvdb",
    "<span>tvdb</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~updatedfile",
    "variable/index.html#static-variable-updatedFile",
    "<span>updatedFile</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~webrequesttimeout",
    "variable/index.html#static-variable-webRequestTimeout",
    "<span>webRequestTimeout</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "popcorn-api/src/config/constants.js~workers",
    "variable/index.html#static-variable-workers",
    "<span>workers</span> <span class=\"search-result-import-path\">popcorn-api/src/config/constants.js</span>",
    "variable"
  ],
  [
    "animes src/controllers/animes.js~animes,animes",
    "test-file/test/controllers/animes.js.html#lineNumber11",
    "Animes:",
    "test"
  ],
  [
    "animes#getanime src/controllers/animes.js~animes#getanime,animes#getanime",
    "test-file/test/controllers/animes.js.html#lineNumber44",
    "Animes: GET /anime/:id",
    "test"
  ],
  [
    "animes#getanimes src/controllers/animes.js~animes#getanimes,animes#getanimes",
    "test-file/test/controllers/animes.js.html#lineNumber21",
    "Animes: GET /animes",
    "test"
  ],
  [
    "animes#getpage src/controllers/animes.js~animes#getpage,animes#getpage",
    "test-file/test/controllers/animes.js.html#lineNumber32",
    "Animes: GET /animes/:page",
    "test"
  ],
  [
    "animes#getrandomanime src/controllers/animes.js~animes#getrandomanime,animes#getrandomanime",
    "test-file/test/controllers/animes.js.html#lineNumber55",
    "Animes: GET /random/anime",
    "test"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "index src/controllers/index.js~index,index",
    "test-file/test/controllers/index.js.html#lineNumber11",
    "Index:",
    "test"
  ],
  [
    "index#geterrorlog src/controllers/index.js~index#geterrorlog,index#geterrorlog",
    "test-file/test/controllers/index.js.html#lineNumber25",
    "Index: GET /logs/error",
    "test"
  ],
  [
    "index#getindex src/controllers/index.js~index#getindex,index#getindex",
    "test-file/test/controllers/index.js.html#lineNumber14",
    "Index: GET /status",
    "test"
  ],
  [
    "movies src/controllers/movies.js~movies,movies",
    "test-file/test/controllers/movies.js.html#lineNumber11",
    "Movies:",
    "test"
  ],
  [
    "movies#getmovie src/controllers/movies.js~movies#getmovie,movies#getmovie",
    "test-file/test/controllers/movies.js.html#lineNumber44",
    "Movies: GET /movie/:id",
    "test"
  ],
  [
    "movies#getmovies src/controllers/movies.js~movies#getmovies,movies#getmovies",
    "test-file/test/controllers/movies.js.html#lineNumber21",
    "Movies: GET /movies",
    "test"
  ],
  [
    "movies#getpage src/controllers/movies.js~movies#getpage,movies#getpage",
    "test-file/test/controllers/movies.js.html#lineNumber32",
    "Movies: GET /movies/:page",
    "test"
  ],
  [
    "movies#getrandommovie src/controllers/movies.js~movies#getrandommovie,movies#getrandommovie",
    "test-file/test/controllers/movies.js.html#lineNumber55",
    "Movies: GET /random/movie",
    "test"
  ],
  [
    "shows src/controllers/shows.js~shows,shows",
    "test-file/test/controllers/shows.js.html#lineNumber11",
    "Shows:",
    "test"
  ],
  [
    "shows#getrandomshow src/controllers/shows.js~shows#getrandomshow,shows#getrandomshow",
    "test-file/test/controllers/shows.js.html#lineNumber59",
    "Shows: GET /random/show",
    "test"
  ],
  [
    "shows#getshow src/controllers/shows.js~shows#getshow,shows#getshow",
    "test-file/test/controllers/shows.js.html#lineNumber48",
    "Shows: GET /show/:id",
    "test"
  ],
  [
    "shows#getshows src/controllers/shows.js~shows#getshows,shows#getshows",
    "test-file/test/controllers/shows.js.html#lineNumber21",
    "Shows: GET /shows",
    "test"
  ],
  [
    "shows#getpage src/controllers/shows.js~shows#getpage,shows#getpage",
    "test-file/test/controllers/shows.js.html#lineNumber32",
    "Shows: GET /shows/:page",
    "test"
  ],
  [
    "src/cli.js",
    "file/src/cli.js.html",
    "src/cli.js",
    "file"
  ],
  [
    "src/cli.js~cli#_animeprompt",
    "class/src/cli.js~CLI.html#instance-method-_animePrompt",
    "src/cli.js~CLI#_animePrompt",
    "method"
  ],
  [
    "src/cli.js~cli#_animeschema",
    "class/src/cli.js~CLI.html#instance-member-_animeSchema",
    "src/cli.js~CLI#_animeSchema",
    "member"
  ],
  [
    "src/cli.js~cli#_getmovietorrentdataremote",
    "class/src/cli.js~CLI.html#instance-method-_getMovieTorrentDataRemote",
    "src/cli.js~CLI#_getMovieTorrentDataRemote",
    "method"
  ],
  [
    "src/cli.js~cli#_getshowtorrentdataremote",
    "class/src/cli.js~CLI.html#instance-method-_getShowTorrentDataRemote",
    "src/cli.js~CLI#_getShowTorrentDataRemote",
    "method"
  ],
  [
    "src/cli.js~cli#_importprompt",
    "class/src/cli.js~CLI.html#instance-method-_importPrompt",
    "src/cli.js~CLI#_importPrompt",
    "method"
  ],
  [
    "src/cli.js~cli#_importschema",
    "class/src/cli.js~CLI.html#instance-member-_importSchema",
    "src/cli.js~CLI#_importSchema",
    "member"
  ],
  [
    "src/cli.js~cli#_movieprompt",
    "class/src/cli.js~CLI.html#instance-method-_moviePrompt",
    "src/cli.js~CLI#_moviePrompt",
    "method"
  ],
  [
    "src/cli.js~cli#_movieschema",
    "class/src/cli.js~CLI.html#instance-member-_movieSchema",
    "src/cli.js~CLI#_movieSchema",
    "member"
  ],
  [
    "src/cli.js~cli#_showprompt",
    "class/src/cli.js~CLI.html#instance-method-_showPrompt",
    "src/cli.js~CLI#_showPrompt",
    "method"
  ],
  [
    "src/cli.js~cli#_showschema",
    "class/src/cli.js~CLI.html#instance-member-_showSchema",
    "src/cli.js~CLI#_showSchema",
    "member"
  ],
  [
    "src/cli.js~cli#_util",
    "class/src/cli.js~CLI.html#instance-member-_util",
    "src/cli.js~CLI#_util",
    "member"
  ],
  [
    "src/cli.js~cli#constructor",
    "class/src/cli.js~CLI.html#instance-constructor-constructor",
    "src/cli.js~CLI#constructor",
    "method"
  ],
  [
    "src/cli.js~cli#run",
    "class/src/cli.js~CLI.html#instance-method-run",
    "src/cli.js~CLI#run",
    "method"
  ],
  [
    "src/config/constants.js",
    "file/src/config/constants.js.html",
    "src/config/constants.js",
    "file"
  ],
  [
    "src/config/logger.js",
    "file/src/config/logger.js.html",
    "src/config/logger.js",
    "file"
  ],
  [
    "src/config/logger.js~expresswinston",
    "external/index.html",
    "src/config/logger.js~ExpressWinston",
    "external"
  ],
  [
    "src/config/logger.js~logger#constructor",
    "class/src/config/logger.js~Logger.html#instance-constructor-constructor",
    "src/config/logger.js~Logger#constructor",
    "method"
  ],
  [
    "src/config/logger.js~logger._checkemptymessage",
    "class/src/config/logger.js~Logger.html#static-method-_checkEmptyMessage",
    "src/config/logger.js~Logger._checkEmptyMessage",
    "method"
  ],
  [
    "src/config/logger.js~logger._consoleformatter",
    "class/src/config/logger.js~Logger.html#static-method-_consoleFormatter",
    "src/config/logger.js~Logger._consoleFormatter",
    "method"
  ],
  [
    "src/config/logger.js~logger._createlogger",
    "class/src/config/logger.js~Logger.html#static-method-_createLogger",
    "src/config/logger.js~Logger._createLogger",
    "method"
  ],
  [
    "src/config/logger.js~logger._fileformatter",
    "class/src/config/logger.js~Logger.html#static-method-_fileFormatter",
    "src/config/logger.js~Logger._fileFormatter",
    "method"
  ],
  [
    "src/config/logger.js~logger._getlevelcolor",
    "class/src/config/logger.js~Logger.html#static-method-_getLevelColor",
    "src/config/logger.js~Logger._getLevelColor",
    "method"
  ],
  [
    "src/config/logger.js~winston",
    "external/index.html",
    "src/config/logger.js~Winston",
    "external"
  ],
  [
    "src/config/routes.js",
    "file/src/config/routes.js.html",
    "src/config/routes.js",
    "file"
  ],
  [
    "src/config/routes.js~routes#constructor",
    "class/src/config/routes.js~Routes.html#instance-constructor-constructor",
    "src/config/routes.js~Routes#constructor",
    "method"
  ],
  [
    "src/config/routes.js~routes._setuproutes",
    "class/src/config/routes.js~Routes.html#static-method-_setupRoutes",
    "src/config/routes.js~Routes._setupRoutes",
    "method"
  ],
  [
    "src/config/setup.js",
    "file/src/config/setup.js.html",
    "src/config/setup.js",
    "file"
  ],
  [
    "src/config/setup.js~setup#constructor",
    "class/src/config/setup.js~Setup.html#instance-constructor-constructor",
    "src/config/setup.js~Setup#constructor",
    "method"
  ],
  [
    "src/config/setup.js~setup.connectmongodb",
    "class/src/config/setup.js~Setup.html#static-method-connectMongoDB",
    "src/config/setup.js~Setup.connectMongoDB",
    "method"
  ],
  [
    "src/controllers/animes.js",
    "file/src/controllers/animes.js.html",
    "src/controllers/animes.js",
    "file"
  ],
  [
    "src/controllers/animes.js~animes#constructor",
    "class/src/controllers/animes.js~Animes.html#instance-constructor-constructor",
    "src/controllers/animes.js~Animes#constructor",
    "method"
  ],
  [
    "src/controllers/animes.js~animes#getanime",
    "class/src/controllers/animes.js~Animes.html#instance-method-getAnime",
    "src/controllers/animes.js~Animes#getAnime",
    "method"
  ],
  [
    "src/controllers/animes.js~animes#getanimes",
    "class/src/controllers/animes.js~Animes.html#instance-method-getAnimes",
    "src/controllers/animes.js~Animes#getAnimes",
    "method"
  ],
  [
    "src/controllers/animes.js~animes#getpage",
    "class/src/controllers/animes.js~Animes.html#instance-method-getPage",
    "src/controllers/animes.js~Animes#getPage",
    "method"
  ],
  [
    "src/controllers/animes.js~animes#getrandomanime",
    "class/src/controllers/animes.js~Animes.html#instance-method-getRandomAnime",
    "src/controllers/animes.js~Animes#getRandomAnime",
    "method"
  ],
  [
    "src/controllers/exports.js",
    "file/src/controllers/exports.js.html",
    "src/controllers/exports.js",
    "file"
  ],
  [
    "src/controllers/exports.js~exports#_util",
    "class/src/controllers/exports.js~Exports.html#instance-member-_util",
    "src/controllers/exports.js~Exports#_util",
    "member"
  ],
  [
    "src/controllers/exports.js~exports#constructor",
    "class/src/controllers/exports.js~Exports.html#instance-constructor-constructor",
    "src/controllers/exports.js~Exports#constructor",
    "method"
  ],
  [
    "src/controllers/exports.js~exports#getexport",
    "class/src/controllers/exports.js~Exports.html#instance-method-getExport",
    "src/controllers/exports.js~Exports#getExport",
    "method"
  ],
  [
    "src/controllers/index.js",
    "file/src/controllers/index.js.html",
    "src/controllers/index.js",
    "file"
  ],
  [
    "src/controllers/index.js~index#constructor",
    "class/src/controllers/index.js~Index.html#instance-constructor-constructor",
    "src/controllers/index.js~Index#constructor",
    "method"
  ],
  [
    "src/controllers/index.js~index#geterrorlog",
    "class/src/controllers/index.js~Index.html#instance-method-getErrorLog",
    "src/controllers/index.js~Index#getErrorLog",
    "method"
  ],
  [
    "src/controllers/index.js~index#getindex",
    "class/src/controllers/index.js~Index.html#instance-method-getIndex",
    "src/controllers/index.js~Index#getIndex",
    "method"
  ],
  [
    "src/controllers/index.js~index._displayfile",
    "class/src/controllers/index.js~Index.html#static-method-_displayFile",
    "src/controllers/index.js~Index._displayFile",
    "method"
  ],
  [
    "src/controllers/movies.js",
    "file/src/controllers/movies.js.html",
    "src/controllers/movies.js",
    "file"
  ],
  [
    "src/controllers/movies.js~movies#constructor",
    "class/src/controllers/movies.js~Movies.html#instance-constructor-constructor",
    "src/controllers/movies.js~Movies#constructor",
    "method"
  ],
  [
    "src/controllers/movies.js~movies#getmovie",
    "class/src/controllers/movies.js~Movies.html#instance-method-getMovie",
    "src/controllers/movies.js~Movies#getMovie",
    "method"
  ],
  [
    "src/controllers/movies.js~movies#getmovies",
    "class/src/controllers/movies.js~Movies.html#instance-method-getMovies",
    "src/controllers/movies.js~Movies#getMovies",
    "method"
  ],
  [
    "src/controllers/movies.js~movies#getpage",
    "class/src/controllers/movies.js~Movies.html#instance-method-getPage",
    "src/controllers/movies.js~Movies#getPage",
    "method"
  ],
  [
    "src/controllers/movies.js~movies#getrandommovie",
    "class/src/controllers/movies.js~Movies.html#instance-method-getRandomMovie",
    "src/controllers/movies.js~Movies#getRandomMovie",
    "method"
  ],
  [
    "src/controllers/shows.js",
    "file/src/controllers/shows.js.html",
    "src/controllers/shows.js",
    "file"
  ],
  [
    "src/controllers/shows.js~shows#constructor",
    "class/src/controllers/shows.js~Shows.html#instance-constructor-constructor",
    "src/controllers/shows.js~Shows#constructor",
    "method"
  ],
  [
    "src/controllers/shows.js~shows#getpage",
    "class/src/controllers/shows.js~Shows.html#instance-method-getPage",
    "src/controllers/shows.js~Shows#getPage",
    "method"
  ],
  [
    "src/controllers/shows.js~shows#getrandomshow",
    "class/src/controllers/shows.js~Shows.html#instance-method-getRandomShow",
    "src/controllers/shows.js~Shows#getRandomShow",
    "method"
  ],
  [
    "src/controllers/shows.js~shows#getshow",
    "class/src/controllers/shows.js~Shows.html#instance-method-getShow",
    "src/controllers/shows.js~Shows#getShow",
    "method"
  ],
  [
    "src/controllers/shows.js~shows#getshows",
    "class/src/controllers/shows.js~Shows.html#instance-method-getShows",
    "src/controllers/shows.js~Shows#getShows",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.js~index#constructor",
    "class/src/index.js~Index.html#instance-constructor-constructor",
    "src/index.js~Index#constructor",
    "method"
  ],
  [
    "src/index.js~index._startapi",
    "class/src/index.js~Index.html#static-method-_startAPI",
    "src/index.js~Index._startAPI",
    "method"
  ],
  [
    "src/index.js~index.closeapi",
    "class/src/index.js~Index.html#static-method-closeAPI",
    "src/index.js~Index.closeAPI",
    "method"
  ],
  [
    "src/models/anime.js",
    "file/src/models/Anime.js.html",
    "src/models/Anime.js",
    "file"
  ],
  [
    "src/models/movie.js",
    "file/src/models/Movie.js.html",
    "src/models/Movie.js",
    "file"
  ],
  [
    "src/models/show.js",
    "file/src/models/Show.js.html",
    "src/models/Show.js",
    "file"
  ],
  [
    "src/popcorn-api.js",
    "file/src/popcorn-api.js.html",
    "src/popcorn-api.js",
    "file"
  ],
  [
    "src/providers/anime/extratorrent.js",
    "file/src/providers/anime/extratorrent.js.html",
    "src/providers/anime/extratorrent.js",
    "file"
  ],
  [
    "src/providers/anime/extratorrent.js~extratorrent#_extractor",
    "class/src/providers/anime/extratorrent.js~ExtraTorrent.html#instance-member-_extractor",
    "src/providers/anime/extratorrent.js~ExtraTorrent#_extractor",
    "member"
  ],
  [
    "src/providers/anime/extratorrent.js~extratorrent#_util",
    "class/src/providers/anime/extratorrent.js~ExtraTorrent.html#instance-member-_util",
    "src/providers/anime/extratorrent.js~ExtraTorrent#_util",
    "member"
  ],
  [
    "src/providers/anime/extratorrent.js~extratorrent#constructor",
    "class/src/providers/anime/extratorrent.js~ExtraTorrent.html#instance-constructor-constructor",
    "src/providers/anime/extratorrent.js~ExtraTorrent#constructor",
    "method"
  ],
  [
    "src/providers/anime/extratorrent.js~extratorrent#name",
    "class/src/providers/anime/extratorrent.js~ExtraTorrent.html#instance-member-name",
    "src/providers/anime/extratorrent.js~ExtraTorrent#name",
    "member"
  ],
  [
    "src/providers/anime/extratorrent.js~extratorrent#search",
    "class/src/providers/anime/extratorrent.js~ExtraTorrent.html#instance-method-search",
    "src/providers/anime/extratorrent.js~ExtraTorrent#search",
    "method"
  ],
  [
    "src/providers/anime/horriblesubs.js",
    "file/src/providers/anime/horriblesubs.js.html",
    "src/providers/anime/horriblesubs.js",
    "file"
  ],
  [
    "src/providers/anime/horriblesubs.js~horriblesubs#_extractor",
    "class/src/providers/anime/horriblesubs.js~HorribleSubs.html#instance-member-_extractor",
    "src/providers/anime/horriblesubs.js~HorribleSubs#_extractor",
    "member"
  ],
  [
    "src/providers/anime/horriblesubs.js~horriblesubs#_horriblesubs",
    "class/src/providers/anime/horriblesubs.js~HorribleSubs.html#instance-member-_horriblesubs",
    "src/providers/anime/horriblesubs.js~HorribleSubs#_horriblesubs",
    "member"
  ],
  [
    "src/providers/anime/horriblesubs.js~horriblesubs#_util",
    "class/src/providers/anime/horriblesubs.js~HorribleSubs.html#instance-member-_util",
    "src/providers/anime/horriblesubs.js~HorribleSubs#_util",
    "member"
  ],
  [
    "src/providers/anime/horriblesubs.js~horriblesubs#constructor",
    "class/src/providers/anime/horriblesubs.js~HorribleSubs.html#instance-constructor-constructor",
    "src/providers/anime/horriblesubs.js~HorribleSubs#constructor",
    "method"
  ],
  [
    "src/providers/anime/horriblesubs.js~horriblesubs#name",
    "class/src/providers/anime/horriblesubs.js~HorribleSubs.html#instance-member-name",
    "src/providers/anime/horriblesubs.js~HorribleSubs#name",
    "member"
  ],
  [
    "src/providers/anime/horriblesubs.js~horriblesubs#search",
    "class/src/providers/anime/horriblesubs.js~HorribleSubs.html#instance-method-search",
    "src/providers/anime/horriblesubs.js~HorribleSubs#search",
    "method"
  ],
  [
    "src/providers/anime/kat.js",
    "file/src/providers/anime/kat.js.html",
    "src/providers/anime/kat.js",
    "file"
  ],
  [
    "src/providers/anime/kat.js~kat#_extractor",
    "class/src/providers/anime/kat.js~KAT.html#instance-member-_extractor",
    "src/providers/anime/kat.js~KAT#_extractor",
    "member"
  ],
  [
    "src/providers/anime/kat.js~kat#_util",
    "class/src/providers/anime/kat.js~KAT.html#instance-member-_util",
    "src/providers/anime/kat.js~KAT#_util",
    "member"
  ],
  [
    "src/providers/anime/kat.js~kat#constructor",
    "class/src/providers/anime/kat.js~KAT.html#instance-constructor-constructor",
    "src/providers/anime/kat.js~KAT#constructor",
    "method"
  ],
  [
    "src/providers/anime/kat.js~kat#name",
    "class/src/providers/anime/kat.js~KAT.html#instance-member-name",
    "src/providers/anime/kat.js~KAT#name",
    "member"
  ],
  [
    "src/providers/anime/kat.js~kat#search",
    "class/src/providers/anime/kat.js~KAT.html#instance-method-search",
    "src/providers/anime/kat.js~KAT#search",
    "method"
  ],
  [
    "src/providers/anime/nyaa.js",
    "file/src/providers/anime/nyaa.js.html",
    "src/providers/anime/nyaa.js",
    "file"
  ],
  [
    "src/providers/anime/nyaa.js~extratorrent#_extractor",
    "class/src/providers/anime/nyaa.js~ExtraTorrent.html#instance-member-_extractor",
    "src/providers/anime/nyaa.js~ExtraTorrent#_extractor",
    "member"
  ],
  [
    "src/providers/anime/nyaa.js~extratorrent#_util",
    "class/src/providers/anime/nyaa.js~ExtraTorrent.html#instance-member-_util",
    "src/providers/anime/nyaa.js~ExtraTorrent#_util",
    "member"
  ],
  [
    "src/providers/anime/nyaa.js~extratorrent#constructor",
    "class/src/providers/anime/nyaa.js~ExtraTorrent.html#instance-constructor-constructor",
    "src/providers/anime/nyaa.js~ExtraTorrent#constructor",
    "method"
  ],
  [
    "src/providers/anime/nyaa.js~extratorrent#name",
    "class/src/providers/anime/nyaa.js~ExtraTorrent.html#instance-member-name",
    "src/providers/anime/nyaa.js~ExtraTorrent#name",
    "member"
  ],
  [
    "src/providers/anime/nyaa.js~extratorrent#search",
    "class/src/providers/anime/nyaa.js~ExtraTorrent.html#instance-method-search",
    "src/providers/anime/nyaa.js~ExtraTorrent#search",
    "method"
  ],
  [
    "src/providers/extractors/animeextractor.js",
    "file/src/providers/extractors/animeextractor.js.html",
    "src/providers/extractors/animeextractor.js",
    "file"
  ],
  [
    "src/providers/extractors/animeextractor.js~extractor#_extractanime",
    "class/src/providers/extractors/animeextractor.js~Extractor.html#instance-method-_extractAnime",
    "src/providers/extractors/animeextractor.js~Extractor#_extractAnime",
    "method"
  ],
  [
    "src/providers/extractors/animeextractor.js~extractor#_getallanimes",
    "class/src/providers/extractors/animeextractor.js~Extractor.html#instance-method-_getAllAnimes",
    "src/providers/extractors/animeextractor.js~Extractor#_getAllAnimes",
    "method"
  ],
  [
    "src/providers/extractors/animeextractor.js~extractor#_getanimedata",
    "class/src/providers/extractors/animeextractor.js~Extractor.html#instance-method-_getAnimeData",
    "src/providers/extractors/animeextractor.js~Extractor#_getAnimeData",
    "method"
  ],
  [
    "src/providers/extractors/animeextractor.js~extractor#_helper",
    "class/src/providers/extractors/animeextractor.js~Extractor.html#instance-member-_helper",
    "src/providers/extractors/animeextractor.js~Extractor#_helper",
    "member"
  ],
  [
    "src/providers/extractors/animeextractor.js~extractor#_util",
    "class/src/providers/extractors/animeextractor.js~Extractor.html#instance-member-_util",
    "src/providers/extractors/animeextractor.js~Extractor#_util",
    "member"
  ],
  [
    "src/providers/extractors/animeextractor.js~extractor#constructor",
    "class/src/providers/extractors/animeextractor.js~Extractor.html#instance-constructor-constructor",
    "src/providers/extractors/animeextractor.js~Extractor#constructor",
    "method"
  ],
  [
    "src/providers/extractors/animeextractor.js~extractor#getanime",
    "class/src/providers/extractors/animeextractor.js~Extractor.html#instance-method-getAnime",
    "src/providers/extractors/animeextractor.js~Extractor#getAnime",
    "method"
  ],
  [
    "src/providers/extractors/animeextractor.js~extractor#search",
    "class/src/providers/extractors/animeextractor.js~Extractor.html#instance-method-search",
    "src/providers/extractors/animeextractor.js~Extractor#search",
    "method"
  ],
  [
    "src/providers/extractors/baseextractor.js",
    "file/src/providers/extractors/baseextractor.js.html",
    "src/providers/extractors/baseextractor.js",
    "file"
  ],
  [
    "src/providers/extractors/baseextractor.js~baseextractor#_contentprovider",
    "class/src/providers/extractors/baseextractor.js~BaseExtractor.html#instance-member-_contentProvider",
    "src/providers/extractors/baseextractor.js~BaseExtractor#_contentProvider",
    "member"
  ],
  [
    "src/providers/extractors/baseextractor.js~baseextractor#_getalltorrents",
    "class/src/providers/extractors/baseextractor.js~BaseExtractor.html#instance-method-_getAllTorrents",
    "src/providers/extractors/baseextractor.js~BaseExtractor#_getAllTorrents",
    "method"
  ],
  [
    "src/providers/extractors/baseextractor.js~baseextractor#_util",
    "class/src/providers/extractors/baseextractor.js~BaseExtractor.html#instance-member-_util",
    "src/providers/extractors/baseextractor.js~BaseExtractor#_util",
    "member"
  ],
  [
    "src/providers/extractors/baseextractor.js~baseextractor#constructor",
    "class/src/providers/extractors/baseextractor.js~BaseExtractor.html#instance-constructor-constructor",
    "src/providers/extractors/baseextractor.js~BaseExtractor#constructor",
    "method"
  ],
  [
    "src/providers/extractors/baseextractor.js~baseextractor#name",
    "class/src/providers/extractors/baseextractor.js~BaseExtractor.html#instance-member-name",
    "src/providers/extractors/baseextractor.js~BaseExtractor#name",
    "member"
  ],
  [
    "src/providers/extractors/movieextractor.js",
    "file/src/providers/extractors/movieextractor.js.html",
    "src/providers/extractors/movieextractor.js",
    "file"
  ],
  [
    "src/providers/extractors/movieextractor.js~extractor#_extractmovie",
    "class/src/providers/extractors/movieextractor.js~Extractor.html#instance-method-_extractMovie",
    "src/providers/extractors/movieextractor.js~Extractor#_extractMovie",
    "method"
  ],
  [
    "src/providers/extractors/movieextractor.js~extractor#_getallmovies",
    "class/src/providers/extractors/movieextractor.js~Extractor.html#instance-method-_getAllMovies",
    "src/providers/extractors/movieextractor.js~Extractor#_getAllMovies",
    "method"
  ],
  [
    "src/providers/extractors/movieextractor.js~extractor#_getmovie",
    "class/src/providers/extractors/movieextractor.js~Extractor.html#instance-method-_getMovie",
    "src/providers/extractors/movieextractor.js~Extractor#_getMovie",
    "method"
  ],
  [
    "src/providers/extractors/movieextractor.js~extractor#_getmoviedata",
    "class/src/providers/extractors/movieextractor.js~Extractor.html#instance-method-_getMovieData",
    "src/providers/extractors/movieextractor.js~Extractor#_getMovieData",
    "method"
  ],
  [
    "src/providers/extractors/movieextractor.js~extractor#_helper",
    "class/src/providers/extractors/movieextractor.js~Extractor.html#instance-member-_helper",
    "src/providers/extractors/movieextractor.js~Extractor#_helper",
    "member"
  ],
  [
    "src/providers/extractors/movieextractor.js~extractor#_util",
    "class/src/providers/extractors/movieextractor.js~Extractor.html#instance-member-_util",
    "src/providers/extractors/movieextractor.js~Extractor#_util",
    "member"
  ],
  [
    "src/providers/extractors/movieextractor.js~extractor#constructor",
    "class/src/providers/extractors/movieextractor.js~Extractor.html#instance-constructor-constructor",
    "src/providers/extractors/movieextractor.js~Extractor#constructor",
    "method"
  ],
  [
    "src/providers/extractors/movieextractor.js~extractor#search",
    "class/src/providers/extractors/movieextractor.js~Extractor.html#instance-method-search",
    "src/providers/extractors/movieextractor.js~Extractor#search",
    "method"
  ],
  [
    "src/providers/extractors/showextractor.js",
    "file/src/providers/extractors/showextractor.js.html",
    "src/providers/extractors/showextractor.js",
    "file"
  ],
  [
    "src/providers/extractors/showextractor.js~extractor#_extractshow",
    "class/src/providers/extractors/showextractor.js~Extractor.html#instance-method-_extractShow",
    "src/providers/extractors/showextractor.js~Extractor#_extractShow",
    "method"
  ],
  [
    "src/providers/extractors/showextractor.js~extractor#_getallshows",
    "class/src/providers/extractors/showextractor.js~Extractor.html#instance-method-_getAllShows",
    "src/providers/extractors/showextractor.js~Extractor#_getAllShows",
    "method"
  ],
  [
    "src/providers/extractors/showextractor.js~extractor#_getshowdata",
    "class/src/providers/extractors/showextractor.js~Extractor.html#instance-method-_getShowData",
    "src/providers/extractors/showextractor.js~Extractor#_getShowData",
    "method"
  ],
  [
    "src/providers/extractors/showextractor.js~extractor#_helper",
    "class/src/providers/extractors/showextractor.js~Extractor.html#instance-member-_helper",
    "src/providers/extractors/showextractor.js~Extractor#_helper",
    "member"
  ],
  [
    "src/providers/extractors/showextractor.js~extractor#_util",
    "class/src/providers/extractors/showextractor.js~Extractor.html#instance-member-_util",
    "src/providers/extractors/showextractor.js~Extractor#_util",
    "member"
  ],
  [
    "src/providers/extractors/showextractor.js~extractor#constructor",
    "class/src/providers/extractors/showextractor.js~Extractor.html#instance-constructor-constructor",
    "src/providers/extractors/showextractor.js~Extractor#constructor",
    "method"
  ],
  [
    "src/providers/extractors/showextractor.js~extractor#getshow",
    "class/src/providers/extractors/showextractor.js~Extractor.html#instance-method-getShow",
    "src/providers/extractors/showextractor.js~Extractor#getShow",
    "method"
  ],
  [
    "src/providers/extractors/showextractor.js~extractor#search",
    "class/src/providers/extractors/showextractor.js~Extractor.html#instance-method-search",
    "src/providers/extractors/showextractor.js~Extractor#search",
    "method"
  ],
  [
    "src/providers/helpers/animehelper.js",
    "file/src/providers/helpers/animehelper.js.html",
    "src/providers/helpers/animehelper.js",
    "file"
  ],
  [
    "src/providers/helpers/animehelper.js~helper#_addseason",
    "class/src/providers/helpers/animehelper.js~Helper.html#instance-method-_addSeason",
    "src/providers/helpers/animehelper.js~Helper#_addSeason",
    "method"
  ],
  [
    "src/providers/helpers/animehelper.js~helper#_hummingbird",
    "class/src/providers/helpers/animehelper.js~Helper.html#instance-member-_hummingbird",
    "src/providers/helpers/animehelper.js~Helper#_hummingbird",
    "member"
  ],
  [
    "src/providers/helpers/animehelper.js~helper#_updateepisode",
    "class/src/providers/helpers/animehelper.js~Helper.html#instance-method-_updateEpisode",
    "src/providers/helpers/animehelper.js~Helper#_updateEpisode",
    "method"
  ],
  [
    "src/providers/helpers/animehelper.js~helper#_updateepisodes",
    "class/src/providers/helpers/animehelper.js~Helper.html#instance-method-_updateEpisodes",
    "src/providers/helpers/animehelper.js~Helper#_updateEpisodes",
    "method"
  ],
  [
    "src/providers/helpers/animehelper.js~helper#_updatenumseasons",
    "class/src/providers/helpers/animehelper.js~Helper.html#instance-method-_updateNumSeasons",
    "src/providers/helpers/animehelper.js~Helper#_updateNumSeasons",
    "method"
  ],
  [
    "src/providers/helpers/animehelper.js~helper#_util",
    "class/src/providers/helpers/animehelper.js~Helper.html#instance-member-_util",
    "src/providers/helpers/animehelper.js~Helper#_util",
    "member"
  ],
  [
    "src/providers/helpers/animehelper.js~helper#addepisodes",
    "class/src/providers/helpers/animehelper.js~Helper.html#instance-method-addEpisodes",
    "src/providers/helpers/animehelper.js~Helper#addEpisodes",
    "method"
  ],
  [
    "src/providers/helpers/animehelper.js~helper#constructor",
    "class/src/providers/helpers/animehelper.js~Helper.html#instance-constructor-constructor",
    "src/providers/helpers/animehelper.js~Helper#constructor",
    "method"
  ],
  [
    "src/providers/helpers/animehelper.js~helper#gethummingbirdinfo",
    "class/src/providers/helpers/animehelper.js~Helper.html#instance-method-getHummingbirdInfo",
    "src/providers/helpers/animehelper.js~Helper#getHummingbirdInfo",
    "method"
  ],
  [
    "src/providers/helpers/animehelper.js~helper#name",
    "class/src/providers/helpers/animehelper.js~Helper.html#instance-member-name",
    "src/providers/helpers/animehelper.js~Helper#name",
    "member"
  ],
  [
    "src/providers/helpers/moviehelper.js",
    "file/src/providers/helpers/moviehelper.js.html",
    "src/providers/helpers/moviehelper.js",
    "file"
  ],
  [
    "src/providers/helpers/moviehelper.js~helper#_getimages",
    "class/src/providers/helpers/moviehelper.js~Helper.html#instance-method-_getImages",
    "src/providers/helpers/moviehelper.js~Helper#_getImages",
    "method"
  ],
  [
    "src/providers/helpers/moviehelper.js~helper#_updatemovie",
    "class/src/providers/helpers/moviehelper.js~Helper.html#instance-method-_updateMovie",
    "src/providers/helpers/moviehelper.js~Helper#_updateMovie",
    "method"
  ],
  [
    "src/providers/helpers/moviehelper.js~helper#_updatetorrent",
    "class/src/providers/helpers/moviehelper.js~Helper.html#instance-method-_updateTorrent",
    "src/providers/helpers/moviehelper.js~Helper#_updateTorrent",
    "method"
  ],
  [
    "src/providers/helpers/moviehelper.js~helper#_util",
    "class/src/providers/helpers/moviehelper.js~Helper.html#instance-member-_util",
    "src/providers/helpers/moviehelper.js~Helper#_util",
    "member"
  ],
  [
    "src/providers/helpers/moviehelper.js~helper#addtorrents",
    "class/src/providers/helpers/moviehelper.js~Helper.html#instance-method-addTorrents",
    "src/providers/helpers/moviehelper.js~Helper#addTorrents",
    "method"
  ],
  [
    "src/providers/helpers/moviehelper.js~helper#constructor",
    "class/src/providers/helpers/moviehelper.js~Helper.html#instance-constructor-constructor",
    "src/providers/helpers/moviehelper.js~Helper#constructor",
    "method"
  ],
  [
    "src/providers/helpers/moviehelper.js~helper#gettraktinfo",
    "class/src/providers/helpers/moviehelper.js~Helper.html#instance-method-getTraktInfo",
    "src/providers/helpers/moviehelper.js~Helper#getTraktInfo",
    "method"
  ],
  [
    "src/providers/helpers/moviehelper.js~helper#name",
    "class/src/providers/helpers/moviehelper.js~Helper.html#instance-member-name",
    "src/providers/helpers/moviehelper.js~Helper#name",
    "member"
  ],
  [
    "src/providers/helpers/showhelper.js",
    "file/src/providers/helpers/showhelper.js.html",
    "src/providers/helpers/showhelper.js",
    "file"
  ],
  [
    "src/providers/helpers/showhelper.js~helper#_adddatebasedseason",
    "class/src/providers/helpers/showhelper.js~Helper.html#instance-method-_addDateBasedSeason",
    "src/providers/helpers/showhelper.js~Helper#_addDateBasedSeason",
    "method"
  ],
  [
    "src/providers/helpers/showhelper.js~helper#_addseasonalseason",
    "class/src/providers/helpers/showhelper.js~Helper.html#instance-method-_addSeasonalSeason",
    "src/providers/helpers/showhelper.js~Helper#_addSeasonalSeason",
    "method"
  ],
  [
    "src/providers/helpers/showhelper.js~helper#_getimages",
    "class/src/providers/helpers/showhelper.js~Helper.html#instance-method-_getImages",
    "src/providers/helpers/showhelper.js~Helper#_getImages",
    "method"
  ],
  [
    "src/providers/helpers/showhelper.js~helper#_updateepisode",
    "class/src/providers/helpers/showhelper.js~Helper.html#instance-method-_updateEpisode",
    "src/providers/helpers/showhelper.js~Helper#_updateEpisode",
    "method"
  ],
  [
    "src/providers/helpers/showhelper.js~helper#_updateepisodes",
    "class/src/providers/helpers/showhelper.js~Helper.html#instance-method-_updateEpisodes",
    "src/providers/helpers/showhelper.js~Helper#_updateEpisodes",
    "method"
  ],
  [
    "src/providers/helpers/showhelper.js~helper#_updatenumseasons",
    "class/src/providers/helpers/showhelper.js~Helper.html#instance-method-_updateNumSeasons",
    "src/providers/helpers/showhelper.js~Helper#_updateNumSeasons",
    "method"
  ],
  [
    "src/providers/helpers/showhelper.js~helper#_util",
    "class/src/providers/helpers/showhelper.js~Helper.html#instance-member-_util",
    "src/providers/helpers/showhelper.js~Helper#_util",
    "member"
  ],
  [
    "src/providers/helpers/showhelper.js~helper#addepisodes",
    "class/src/providers/helpers/showhelper.js~Helper.html#instance-method-addEpisodes",
    "src/providers/helpers/showhelper.js~Helper#addEpisodes",
    "method"
  ],
  [
    "src/providers/helpers/showhelper.js~helper#constructor",
    "class/src/providers/helpers/showhelper.js~Helper.html#instance-constructor-constructor",
    "src/providers/helpers/showhelper.js~Helper#constructor",
    "method"
  ],
  [
    "src/providers/helpers/showhelper.js~helper#gettraktinfo",
    "class/src/providers/helpers/showhelper.js~Helper.html#instance-method-getTraktInfo",
    "src/providers/helpers/showhelper.js~Helper#getTraktInfo",
    "method"
  ],
  [
    "src/providers/helpers/showhelper.js~helper#name",
    "class/src/providers/helpers/showhelper.js~Helper.html#instance-member-name",
    "src/providers/helpers/showhelper.js~Helper#name",
    "member"
  ],
  [
    "src/providers/movies/extratorrent.js",
    "file/src/providers/movies/extratorrent.js.html",
    "src/providers/movies/extratorrent.js",
    "file"
  ],
  [
    "src/providers/movies/extratorrent.js~extratorrent#_extractor",
    "class/src/providers/movies/extratorrent.js~ExtraTorrent.html#instance-member-_extractor",
    "src/providers/movies/extratorrent.js~ExtraTorrent#_extractor",
    "member"
  ],
  [
    "src/providers/movies/extratorrent.js~extratorrent#_util",
    "class/src/providers/movies/extratorrent.js~ExtraTorrent.html#instance-member-_util",
    "src/providers/movies/extratorrent.js~ExtraTorrent#_util",
    "member"
  ],
  [
    "src/providers/movies/extratorrent.js~extratorrent#constructor",
    "class/src/providers/movies/extratorrent.js~ExtraTorrent.html#instance-constructor-constructor",
    "src/providers/movies/extratorrent.js~ExtraTorrent#constructor",
    "method"
  ],
  [
    "src/providers/movies/extratorrent.js~extratorrent#name",
    "class/src/providers/movies/extratorrent.js~ExtraTorrent.html#instance-member-name",
    "src/providers/movies/extratorrent.js~ExtraTorrent#name",
    "member"
  ],
  [
    "src/providers/movies/extratorrent.js~extratorrent#search",
    "class/src/providers/movies/extratorrent.js~ExtraTorrent.html#instance-method-search",
    "src/providers/movies/extratorrent.js~ExtraTorrent#search",
    "method"
  ],
  [
    "src/providers/movies/kat.js",
    "file/src/providers/movies/kat.js.html",
    "src/providers/movies/kat.js",
    "file"
  ],
  [
    "src/providers/movies/kat.js~kat#_extractor",
    "class/src/providers/movies/kat.js~KAT.html#instance-member-_extractor",
    "src/providers/movies/kat.js~KAT#_extractor",
    "member"
  ],
  [
    "src/providers/movies/kat.js~kat#_util",
    "class/src/providers/movies/kat.js~KAT.html#instance-member-_util",
    "src/providers/movies/kat.js~KAT#_util",
    "member"
  ],
  [
    "src/providers/movies/kat.js~kat#constructor",
    "class/src/providers/movies/kat.js~KAT.html#instance-constructor-constructor",
    "src/providers/movies/kat.js~KAT#constructor",
    "method"
  ],
  [
    "src/providers/movies/kat.js~kat#name",
    "class/src/providers/movies/kat.js~KAT.html#instance-member-name",
    "src/providers/movies/kat.js~KAT#name",
    "member"
  ],
  [
    "src/providers/movies/kat.js~kat#search",
    "class/src/providers/movies/kat.js~KAT.html#instance-method-search",
    "src/providers/movies/kat.js~KAT#search",
    "method"
  ],
  [
    "src/providers/movies/yts.js",
    "file/src/providers/movies/yts.js.html",
    "src/providers/movies/yts.js",
    "file"
  ],
  [
    "src/providers/movies/yts.js~yts#_formatpage",
    "class/src/providers/movies/yts.js~YTS.html#instance-method-_formatPage",
    "src/providers/movies/yts.js~YTS#_formatPage",
    "method"
  ],
  [
    "src/providers/movies/yts.js~yts#_getmovies",
    "class/src/providers/movies/yts.js~YTS.html#instance-method-_getMovies",
    "src/providers/movies/yts.js~YTS#_getMovies",
    "method"
  ],
  [
    "src/providers/movies/yts.js~yts#_getonepage",
    "class/src/providers/movies/yts.js~YTS.html#instance-method-_getOnePage",
    "src/providers/movies/yts.js~YTS#_getOnePage",
    "method"
  ],
  [
    "src/providers/movies/yts.js~yts#_gettotalpages",
    "class/src/providers/movies/yts.js~YTS.html#instance-method-_getTotalPages",
    "src/providers/movies/yts.js~YTS#_getTotalPages",
    "method"
  ],
  [
    "src/providers/movies/yts.js~yts#_helper",
    "class/src/providers/movies/yts.js~YTS.html#instance-member-_helper",
    "src/providers/movies/yts.js~YTS#_helper",
    "member"
  ],
  [
    "src/providers/movies/yts.js~yts#_request",
    "class/src/providers/movies/yts.js~YTS.html#instance-member-_request",
    "src/providers/movies/yts.js~YTS#_request",
    "member"
  ],
  [
    "src/providers/movies/yts.js~yts#_util",
    "class/src/providers/movies/yts.js~YTS.html#instance-member-_util",
    "src/providers/movies/yts.js~YTS#_util",
    "member"
  ],
  [
    "src/providers/movies/yts.js~yts#constructor",
    "class/src/providers/movies/yts.js~YTS.html#instance-constructor-constructor",
    "src/providers/movies/yts.js~YTS#constructor",
    "method"
  ],
  [
    "src/providers/movies/yts.js~yts#name",
    "class/src/providers/movies/yts.js~YTS.html#instance-member-name",
    "src/providers/movies/yts.js~YTS#name",
    "member"
  ],
  [
    "src/providers/movies/yts.js~yts#search",
    "class/src/providers/movies/yts.js~YTS.html#instance-method-search",
    "src/providers/movies/yts.js~YTS#search",
    "method"
  ],
  [
    "src/providers/shows/extratorrent.js",
    "file/src/providers/shows/extratorrent.js.html",
    "src/providers/shows/extratorrent.js",
    "file"
  ],
  [
    "src/providers/shows/extratorrent.js~extratorrent#_extractor",
    "class/src/providers/shows/extratorrent.js~ExtraTorrent.html#instance-member-_extractor",
    "src/providers/shows/extratorrent.js~ExtraTorrent#_extractor",
    "member"
  ],
  [
    "src/providers/shows/extratorrent.js~extratorrent#_util",
    "class/src/providers/shows/extratorrent.js~ExtraTorrent.html#instance-member-_util",
    "src/providers/shows/extratorrent.js~ExtraTorrent#_util",
    "member"
  ],
  [
    "src/providers/shows/extratorrent.js~extratorrent#constructor",
    "class/src/providers/shows/extratorrent.js~ExtraTorrent.html#instance-constructor-constructor",
    "src/providers/shows/extratorrent.js~ExtraTorrent#constructor",
    "method"
  ],
  [
    "src/providers/shows/extratorrent.js~extratorrent#name",
    "class/src/providers/shows/extratorrent.js~ExtraTorrent.html#instance-member-name",
    "src/providers/shows/extratorrent.js~ExtraTorrent#name",
    "member"
  ],
  [
    "src/providers/shows/extratorrent.js~extratorrent#search",
    "class/src/providers/shows/extratorrent.js~ExtraTorrent.html#instance-method-search",
    "src/providers/shows/extratorrent.js~ExtraTorrent#search",
    "method"
  ],
  [
    "src/providers/shows/eztv.js",
    "file/src/providers/shows/eztv.js.html",
    "src/providers/shows/eztv.js",
    "file"
  ],
  [
    "src/providers/shows/eztv.js~eztv#_extractor",
    "class/src/providers/shows/eztv.js~EZTV.html#instance-member-_extractor",
    "src/providers/shows/eztv.js~EZTV#_extractor",
    "member"
  ],
  [
    "src/providers/shows/eztv.js~eztv#_eztv",
    "class/src/providers/shows/eztv.js~EZTV.html#instance-member-_eztv",
    "src/providers/shows/eztv.js~EZTV#_eztv",
    "member"
  ],
  [
    "src/providers/shows/eztv.js~eztv#_util",
    "class/src/providers/shows/eztv.js~EZTV.html#instance-member-_util",
    "src/providers/shows/eztv.js~EZTV#_util",
    "member"
  ],
  [
    "src/providers/shows/eztv.js~eztv#constructor",
    "class/src/providers/shows/eztv.js~EZTV.html#instance-constructor-constructor",
    "src/providers/shows/eztv.js~EZTV#constructor",
    "method"
  ],
  [
    "src/providers/shows/eztv.js~eztv#name",
    "class/src/providers/shows/eztv.js~EZTV.html#instance-member-name",
    "src/providers/shows/eztv.js~EZTV#name",
    "member"
  ],
  [
    "src/providers/shows/eztv.js~eztv#search",
    "class/src/providers/shows/eztv.js~EZTV.html#instance-method-search",
    "src/providers/shows/eztv.js~EZTV#search",
    "method"
  ],
  [
    "src/providers/shows/kat.js",
    "file/src/providers/shows/kat.js.html",
    "src/providers/shows/kat.js",
    "file"
  ],
  [
    "src/providers/shows/kat.js~kat#_extractor",
    "class/src/providers/shows/kat.js~KAT.html#instance-member-_extractor",
    "src/providers/shows/kat.js~KAT#_extractor",
    "member"
  ],
  [
    "src/providers/shows/kat.js~kat#_util",
    "class/src/providers/shows/kat.js~KAT.html#instance-member-_util",
    "src/providers/shows/kat.js~KAT#_util",
    "member"
  ],
  [
    "src/providers/shows/kat.js~kat#constructor",
    "class/src/providers/shows/kat.js~KAT.html#instance-constructor-constructor",
    "src/providers/shows/kat.js~KAT#constructor",
    "method"
  ],
  [
    "src/providers/shows/kat.js~kat#name",
    "class/src/providers/shows/kat.js~KAT.html#instance-member-name",
    "src/providers/shows/kat.js~KAT#name",
    "member"
  ],
  [
    "src/providers/shows/kat.js~kat#search",
    "class/src/providers/shows/kat.js~KAT.html#instance-method-search",
    "src/providers/shows/kat.js~KAT#search",
    "method"
  ],
  [
    "src/scraper.js",
    "file/src/scraper.js.html",
    "src/scraper.js",
    "file"
  ],
  [
    "src/scraper.js~scraper#_scrapeeztvshows",
    "class/src/scraper.js~Scraper.html#instance-method-_scrapeEZTVShows",
    "src/scraper.js~Scraper#_scrapeEZTVShows",
    "method"
  ],
  [
    "src/scraper.js~scraper#_scrapeextratorrentanime",
    "class/src/scraper.js~Scraper.html#instance-method-_scrapeExtraTorrentAnime",
    "src/scraper.js~Scraper#_scrapeExtraTorrentAnime",
    "method"
  ],
  [
    "src/scraper.js~scraper#_scrapeextratorrentmovies",
    "class/src/scraper.js~Scraper.html#instance-method-_scrapeExtraTorrentMovies",
    "src/scraper.js~Scraper#_scrapeExtraTorrentMovies",
    "method"
  ],
  [
    "src/scraper.js~scraper#_scrapeextratorrentshows",
    "class/src/scraper.js~Scraper.html#instance-method-_scrapeExtraTorrentShows",
    "src/scraper.js~Scraper#_scrapeExtraTorrentShows",
    "method"
  ],
  [
    "src/scraper.js~scraper#_scrapehorriblesubsanime",
    "class/src/scraper.js~Scraper.html#instance-method-_scrapeHorribleSubsAnime",
    "src/scraper.js~Scraper#_scrapeHorribleSubsAnime",
    "method"
  ],
  [
    "src/scraper.js~scraper#_scrapekatanime",
    "class/src/scraper.js~Scraper.html#instance-method-_scrapeKATAnime",
    "src/scraper.js~Scraper#_scrapeKATAnime",
    "method"
  ],
  [
    "src/scraper.js~scraper#_scrapekatmovies",
    "class/src/scraper.js~Scraper.html#instance-method-_scrapeKATMovies",
    "src/scraper.js~Scraper#_scrapeKATMovies",
    "method"
  ],
  [
    "src/scraper.js~scraper#_scrapekatshows",
    "class/src/scraper.js~Scraper.html#instance-method-_scrapeKATShows",
    "src/scraper.js~Scraper#_scrapeKATShows",
    "method"
  ],
  [
    "src/scraper.js~scraper#_scrapenyaaanime",
    "class/src/scraper.js~Scraper.html#instance-method-_scrapeNyaaAnime",
    "src/scraper.js~Scraper#_scrapeNyaaAnime",
    "method"
  ],
  [
    "src/scraper.js~scraper#_scrapeytsmovies",
    "class/src/scraper.js~Scraper.html#instance-method-_scrapeYTSMovies",
    "src/scraper.js~Scraper#_scrapeYTSMovies",
    "method"
  ],
  [
    "src/scraper.js~scraper#constructor",
    "class/src/scraper.js~Scraper.html#instance-constructor-constructor",
    "src/scraper.js~Scraper#constructor",
    "method"
  ],
  [
    "src/scraper.js~scraper#scrape",
    "class/src/scraper.js~Scraper.html#instance-method-scrape",
    "src/scraper.js~Scraper#scrape",
    "method"
  ],
  [
    "src/util.js",
    "file/src/util.js.html",
    "src/util.js",
    "file"
  ],
  [
    "src/util.js~util#_createemptyfile",
    "class/src/util.js~Util.html#instance-method-_createEmptyFile",
    "src/util.js~Util#_createEmptyFile",
    "method"
  ],
  [
    "src/util.js~util#_resettemp",
    "class/src/util.js~Util.html#instance-method-_resetTemp",
    "src/util.js~Util#_resetTemp",
    "method"
  ],
  [
    "src/util.js~util#createtemp",
    "class/src/util.js~Util.html#instance-method-createTemp",
    "src/util.js~Util#createTemp",
    "method"
  ],
  [
    "src/util.js~util#executecommand",
    "class/src/util.js~Util.html#instance-method-executeCommand",
    "src/util.js~Util#executeCommand",
    "method"
  ],
  [
    "src/util.js~util#exportcollection",
    "class/src/util.js~Util.html#instance-method-exportCollection",
    "src/util.js~Util#exportCollection",
    "method"
  ],
  [
    "src/util.js~util#importcollection",
    "class/src/util.js~Util.html#instance-method-importCollection",
    "src/util.js~Util#importCollection",
    "method"
  ],
  [
    "src/util.js~util#onerror",
    "class/src/util.js~Util.html#instance-method-onError",
    "src/util.js~Util#onError",
    "method"
  ],
  [
    "src/util.js~util#resetlog",
    "class/src/util.js~Util.html#instance-method-resetLog",
    "src/util.js~Util#resetLog",
    "method"
  ],
  [
    "src/util.js~util#search",
    "class/src/util.js~Util.html#instance-method-search",
    "src/util.js~Util#search",
    "method"
  ],
  [
    "src/util.js~util#setlastupdated",
    "class/src/util.js~Util.html#instance-method-setLastUpdated",
    "src/util.js~Util#setLastUpdated",
    "method"
  ],
  [
    "src/util.js~util#setstatus",
    "class/src/util.js~Util.html#instance-method-setStatus",
    "src/util.js~Util#setStatus",
    "method"
  ],
  [
    "test/controllers/animes.js",
    "test-file/test/controllers/animes.js.html",
    "test/controllers/animes.js",
    "testFile"
  ],
  [
    "test/controllers/index.js",
    "test-file/test/controllers/index.js.html",
    "test/controllers/index.js",
    "testFile"
  ],
  [
    "test/controllers/movies.js",
    "test-file/test/controllers/movies.js.html",
    "test/controllers/movies.js",
    "testFile"
  ],
  [
    "test/controllers/shows.js",
    "test-file/test/controllers/shows.js.html",
    "test/controllers/shows.js",
    "testFile"
  ]
]